let paises = [
    {
        titulo: "Brasil",
        nomeOficial: "República Federativa do Brasil",
        descricao: "O Brasil é um país de dimensões continentais, localizado na América do Sul. Conhecido por sua rica biodiversidade, paisagens exuberantes e uma cultura vibrante, o Brasil é um verdadeiro caldeirão de etnias e tradições",
        codigoISO: "BRA",
        festasNacionais: "Carnaval Festa Junina Corpus Christi Semana Santa Natal",
        capital: "Brasília",
        populacao: "205.223.000",
        atualPresidente: "Luiz Inácio Lula da Silva",
        idioma: "Português",
        monetario: "Real (R$)",
        imagem: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png",
        link: "https://www.britannica.com/place/Brazil"
    },
    {
        titulo: "Canadá",
        nomeOficial: "Canadá",
        descricao: "O Canadá é um país da América do Norte, conhecido por suas paisagens frias e montanhosas, seus lagos numerosos e sua rica diversidade cultural. É um país bilingue, com o inglês e o francês como línguas oficiais.",
        codigoISO: "CAN",
        festasNacionais: "Dia do Canadá, Natal, Ano Novo",
        capital: "Ottawa",
        populacao: "38.248.496",
        atualPresidente: "Não possui (Chefe de Estado: Rei Charles III, Chefe de Governo: Justin Trudeau)",
        idioma: "Inglês, Francês",
        monetario: "Dólar canadense ($)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Toronto_-_ON_-_Toronto_Harbourfront7.jpg/640px-Toronto_-_ON_-_Toronto_Harbourfront7.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/640px-Flag_of_Canada_%28Pantone%29.svg.png",
        link: "https://www.britannica.com/place/Canada"
      },
      {
        titulo: "México",
        nomeOficial: "Estados Unidos Mexicanos",
        descricao: "O México é um país da América do Norte, conhecido por suas ricas tradições culturais, sua história pré-hispânica e suas belas paisagens, que vão desde desertos até praias paradisíacas. É um país com uma grande diversidade cultural e linguística.",
        codigoISO: "MEX",
        festasNacionais: "Dia da Independência do México, Dia dos Mortos",
        capital: "Cidade do México",
        populacao: "128.932.753",
        atualPresidente: "Andrés Manuel López Obrador",
        idioma: "Espanhol",
        monetario: "Peso mexicano ($)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Angel_of_Independence_%28Angel_de_la_Independencia%29.jpg/640px-Angel_of_Independence_%28Angel_de_la_Independencia%29.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/640px-Flag_of_Mexico.svg.png",
        link: "https://www.britannica.com/place/Mexico"
      },
      {
        titulo: "Japão",
        nomeOficial: "Japão",
        descricao: "O Japão é um arquipélago localizado no Oceano Pacífico, conhecido por sua rica cultura, tecnologia avançada e paisagens montanhosas. Sua história milenar, tradições milenares e a cultura pop única o tornam um dos países mais fascinantes do mundo.",
        codigoISO: "JPN",
        festasNacionais: "Ano Novo, Dia do Mar, Dia da Constituição",
        capital: "Tóquio",
        populacao: "125.500.000",
        atualPresidente: "Não possui (Chefe de Estado: Imperador Naruhito, Chefe de Governo: Fumio Kishida)",
        idioma: "Japonês",
        monetario: "Iene (¥)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Nara%2C_panor%C3%A1micas_%282005%29_02.jpg/640px-Nara%2C_panor%C3%A1micas_%282005%29_02.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png",
        link: "https://www.britannica.com/place/Japan"
      },
      {
        titulo: "China",
        nomeOficial: "República Popular da China",
        descricao: "A China é a civilização mais antiga do mundo, com uma rica história e cultura. É um país de contrastes, com megacidades modernas e áreas rurais tradicionais. A China é uma potência econômica mundial e um líder em tecnologia.",
        codigoISO: "CHN",
        festasNacionais: "Ano Novo Lunar, Dia Nacional da República Popular da China",
        capital: "Pequim",
        populacao: "1.411.778.724",
        atualPresidente: "Xi Jinping",
        idioma: "Mandarim",
        monetario: "Yuan (¥)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Great_Wall_of_China_July_2006.JPG/640px-Great_Wall_of_China_July_2006.JPG",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1280px-Flag_of_the_People%2s_Que_s.svg.png",
        link: "https://www.britannica.com/place/China"
      },
      {
        titulo: "Noruega",
        nomeOficial: "Reino da Noruega",
        descricao: "A Noruega é um país escandinavo, conhecido por suas paisagens montanhosas, fiordes dramáticos e auroras boreais. É um país com uma alta qualidade de vida e um forte compromisso com a sustentabilidade.",
        codigoISO: "NOR",
        festasNacionais: "Dia da Constituição",
        capital: "Oslo",
        populacao: "5.421.000",
        atualPresidente: "Chefe de Estado: Rei Harald V, Chefe de Governo: Jonas Gahr Støre",
        idioma: "Norueguês",
        monetario: "Coroa norueguesa (kr)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Oslo_palace1.jpg/640px-Oslo_palace1.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Flag_of_Norway_%28c8102e_for_red_%26_00205b_for_blue%29.svg/640px-Flag_of_Norway_%28c8102e_for_red_%26_00205b_for_blue%29.svg.png"
      },
      {
        titulo: "Coreia do Sul",
        nomeOficial: "República da Coreia",
        descricao: "A Coreia do Sul é um país asiático conhecido por sua cultura pop vibrante, tecnologia avançada e paisagens montanhosas. É uma potência econômica global e um centro tecnológico inovador.",
        codigoISO: "KOR",
        festasNacionais: "Dia da Independência, Seollal (Ano Novo Lunar)",
        capital: "Seul",
        populacao: "51.849.169",
        atualPresidente: "Yoon Suk-yeol",
        idioma: "Coreano",
        monetario: "Won sul-coreano (₩)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Seoul_%28175734251%29.jpeg/640px-Seoul_%28175734251%29.jpeg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1280px-Flag_of_South_Korea.svg.png",
        link: "https://www.britannica.com/place/South-Korea"
      },
      {
        titulo: "Ucrânia",
        nomeOficial: "Ucrânia",
        descricao: "A Ucrânia é um país localizado na Europa Oriental, com uma rica história e cultura. Conhecida por suas paisagens diversas, desde as planícies até os Cárpatos, a Ucrânia tem enfrentado desafios significativos nos últimos anos, incluindo um conflito armado em seu território.",
        codigoISO: "UKR",
        festasNacionais: "Dia da Independência",
        capital: "Kiev",
        populacao: "41.614.206",
        atualPresidente: "Volodymyr Zelenskyy",
        idioma: "Ucraniano",
        monetario: "Hryvnia (₴)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Fishermen_on_the_Dnieper_ryver._Kiev%2C_Ukraine.jpg/640px-Fishermen_on_the_Dnieper_ryver._Kiev%2C_Ukraine.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/1280px-Flag_of_Ukraine.svg.png",
        link: "https://www.britannica.com/place/Ukraine"
      },
      {
        titulo: "Rússia",
        nomeOficial: "Federação Russa",
        descricao: "A Rússia é a maior nação do mundo, com uma vasta extensão territorial que se estende por dois continentes. Sua história rica e complexa, marcada por impérios e revoluções, moldou uma cultura diversificada. A Rússia é uma potência nuclear e desempenha um papel importante na política global.",
        codigoISO: "RUS",
        festasNacionais: "Dia da Vitória",
        capital: "Moscou",
        populacao: "144.526.636",
        atualPresidente: "Vladimir Putin",
        idioma: "Russo",
        monetario: "Rublo (₽)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Moscow_July_2011-16.jpg/640px-Moscow_July_2011-16.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/1280px-Flag_of_Russia.svg.png",
        link: "https://www.britannica.com/place/Russia"
      },
      {
        titulo: "Portugal",
        nomeOficial: "República Portuguesa",
        descricao: "Portugal é um país ibérico com uma longa história e cultura. Conhecido por suas paisagens diversas, desde as praias do Algarve até as montanhas do norte, Portugal é um destino turístico popular. É também um país com uma forte identidade nacional e uma língua única.",
        codigoISO: "PRT",
        festasNacionais: "Dia de Portugal, de Camões e das Comunidades Portuguesas",
        capital: "Lisboa",
        populacao: "10.276.186",
        atualPresidente: "Marcelo Rebelo de Sousa",
        idioma: "Português",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Torre_de_Bel%C3%A9m%2C_Lisboa%2C_Portugal%2C_2012-05-12%2C_DD_16.JPG/640px-Torre_de_Bel%C3%A9m%2C_Lisboa%2C_Portugal%2C_2012-05-12%2C_DD_16.JPG",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png",
        link: "https://www.britannica.com/place/Portugal"
      },
      {
        titulo: "Espanha",
        nomeOficial: "Reino de Espanha",
        descricao: "A Espanha é um país ibérico com uma rica história e cultura. Conhecida por suas paisagens diversas, desde as praias da Costa del Sol até as montanhas dos Pirenéus, a Espanha é um destino turístico popular. É também um país com uma forte identidade nacional e uma língua única.",
        codigoISO: "ESP",
        festasNacionais: "Dia Nacional da Espanha",
        capital: "Madrid",
        populacao: "47.351.550",
        atualPresidente: "Pedro Sánchez",
        idioma: "Espanhol",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Sagrada_Fam%C3%ADlia_-_P1100496.jpg/640px-Sagrada_Fam%C3%ADlia_-_P1100496.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1280px-Flag_of_Spain.svg.png",
        link: "https://www.britannica.com/place/Spain"
      },
      {
        titulo: "Argentina",
        nomeOficial: "República Argentina",
        descricao: "A Argentina é um país da América do Sul conhecido por sua diversidade geográfica, desde a exuberante Patagônia até as vinícolas de Mendoza. Sua história é marcada por influências europeias e uma forte identidade nacional. A Argentina é um país com uma rica cultura, gastronomia e futebol.",
        codigoISO: "ARG",
        festasNacionais: "Dia da Independência",
        capital: "Buenos Aires",
        populacao: "45.376.763",
        atualPresidente: "Alberto Fernández",
        idioma: "Espanhol",
        monetario: "Peso argentino ($)",
        imagem: "https://th.bing.com/th/id/R.06b6421757f1f8ea63f6435852f8aad3?rik=Pk5400lJxzKSwA&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f2%2f2c%2fBuenos_Aires-Plaza_Congreso-Pensador_de_Rodin.jpg&ehk=aU8G4aYn9Z5ZDbvowV9jAnjsSCdj6k%2fv%2b3Ov61lxer8%3d&risl=&pid=ImgRaw&r=0",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1280px-Flag_of_Argentina.svg.png",
        link: "https://www.britannica.com/place/Argentina"
      },
      {
        titulo: "Peru",
        nomeOficial: "República do Peru",
        descricao: "O Peru é um país da América do Sul com uma rica história que se estende desde as antigas civilizações inca e pré-inca até a época colonial. Conhecido por Machu Picchu, uma das Sete Maravilhas do Mundo Moderno, o Peru oferece uma diversidade de paisagens, desde a costa do Pacífico até a Amazônia. A culinária peruana é considerada uma das melhores do mundo.",
        codigoISO: "PER",
        festasNacionais: "Dia da Independência",
        capital: "Lima",
        populacao: "33.238.755",
        atualPresidente: "Dina Boluarte",
        idioma: "Espanhol (oficial), Quechua, Aymara",
        monetario: "Sol peruano (S/.)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Machu_Picchu%2C_Per%C3%BA%2C_2015-07-30%2C_DD_47.JPG/640px-Machu_Picchu%2C_Per%C3%BA%2C_2015-07-30%2C_DD_47.JPG",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Peru_%28state%29.svg/640px-Flag_of_Peru_%28state%29.svg.png",
        link: "https://www.britannica.com/place/Peru"
      },
      {
        titulo: "Chile",
        nomeOficial: "República do Chile",
        descricao: "O Chile é um país estreito e longo na América do Sul, conhecido por suas paisagens contrastantes, desde o deserto do Atacama até os lagos e vulcões da Patagônia. Sua história é marcada pela colonização espanhola e por um período de ditadura. O Chile é um país com uma forte cultura, gastronomia e tradição vinícola.",
        codigoISO: "CHL",
        festasNacionais: "Dia da Independência",
        capital: "Santiago",
        populacao: "19.116.201",
        atualPresidente: "Gabriel Boric",
        idioma: "Espanhol",
        monetario: "Peso chileno ($)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Cordilheira_dos_Andes_-_Santiago_-_Chile.JPG/640px-Cordilheira_dos_Andes_-_Santiago_-_Chile.JPG",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/1280px-Flag_of_Chile.svg.png",
        link: "https://www.britannica.com/place/Chile"
      },
      {
        titulo: "Colômbia",
        nomeOficial: "República da Colômbia",
        descricao: "A Colômbia é um país da América do Sul conhecido por sua diversidade geográfica, desde a Cordilheira dos Andes até a Amazônia. Sua história é marcada pela colonização espanhola e por um período de conflito armado. A Colômbia é um país com uma rica cultura, gastronomia e biodiversidade.",
        codigoISO: "COL",
        festasNacionais: "Dia da Independência",
        capital: "Bogotá",
        populacao: "51.119.644",
        atualPresidente: "Gustavo Petro",
        idioma: "Espanhol",
        monetario: "Peso colombiano ($)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Bogota%2C_Colombia_%2836668708290%29.jpg/640px-Bogota%2C_Colombia_%2836668708290%29.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/640px-Flag_of_Colombia.svg.png",
        link: "https://www.britannica.com/place/Colombia"
      },
      {
        titulo: "Bolívia",
        nomeOficial: "Estado Plurinacional da Bolívia",
        descricao: "A Bolívia é um país andino com uma rica história pré-colombiana e uma diversidade cultural única. Conhecida por seus Andes majestosos, o Salar de Uyuni e a Amazônia boliviana, a Bolívia oferece paisagens deslumbrantes e uma cultura vibrante. A população boliviana é majoritariamente indígena.",
        codigoISO: "BOL",
        festasNacionais: "Dia da Independência",
        capital: "Sucre (oficial), La Paz (sede de governo)",
        populacao: "11.854.535",
        atualPresidente: "Luis Arce",
        idioma: "Espanhol (oficial), Quechua, Aymara",
        monetario: "Boliviano (Bs.)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/La_Paz-center.jpg/640px-La_Paz-center.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bandera_de_Bolivia_%28Estado%29.svg/640px-Bandera_de_Bolivia_%28Estado%29.svg.png",
        link: "https://www.britannica.com/place/Bolivia"
      },
      {
        titulo: "Uruguai",
        nomeOficial: "República Oriental do Uruguai",
        descricao: "O Uruguai é um país sul-americano conhecido por suas paisagens campestres, praias e cidades históricas. Sua história é marcada pela colonização espanhola e por um período de prosperidade econômica. O Uruguai é um país com uma forte cultura, gastronomia e tradição futebolística.",
        codigoISO: "URY",
        festasNacionais: "Dia da Independência",
        capital: "Montevidéu",
        populacao: "3.461.749",
        atualPresidente: "Luis Lacalle Pou",
        idioma: "Espanhol",
        monetario: "Peso uruguaio ($)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/PALACIO_LEGISLATIVO_01.JPG/640px-PALACIO_LEGISLATIVO_01.JPG",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/640px-Flag_of_Uruguay.svg.png",
        link: "https://www.britannica.com/place/Uruguay"
      },
      {
        titulo: "Venezuela",
        nomeOficial: "República Bolivariana da Venezuela",
        descricao: "A Venezuela é um país sul-americano com uma rica história, cultura e diversidade geográfica. Conhecida por suas reservas de petróleo, a Venezuela possui desde as montanhas dos Andes até as planícies do Orinoco. A cultura venezuelana é uma mistura de influências indígenas, espanholas e africanas.",
        codigoISO: "VEN",
        festasNacionais: "Dia da Independência",
        capital: "Caracas",
        populacao: "28.435.941",
        atualPresidente: "Nicolás Maduro",
        idioma: "Espanhol",
        monetario: "Bolívar Soberano (Bs.S.)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Plaza_Venezuela_Sunset.jpg/640px-Plaza_Venezuela_Sunset.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Flag_of_Venezuela_%28state%29.svg/640px-Flag_of_Venezuela_%28state%29.svg.png",
        link: "https://www.britannica.com/place/Venezuela"
      },
      {
        titulo: "Paraguai",
        nomeOficial: "República do Paraguai",
        descricao: "O Paraguai é um país sul-americano sem litoral, conhecido por suas paisagens naturais exuberantes, como a região dos saltos do Rio Paraná. Sua história é marcada pela Guerra do Paraguai, um conflito que deixou profundas marcas no país. A cultura paraguaia é uma rica mistura de influências indígenas, espanholas e guarani.",
        codigoISO: "PRY",
        festasNacionais: "Dia da Independência",
        capital: "Assunção",
        populacao: "7.132.532",
        atualPresidente: "Mario Abdo Benítez",
        idioma: "Espanhol e Guarani (ambos oficiais)",
        monetario: "Guarani (₲)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Palacio_de_Gobierno2.jpg/640px-Palacio_de_Gobierno2.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Bandera_de_Paraguay_%281954-1988%29.png/640px-Bandera_de_Paraguay_%281954-1988%29.png",
        link: "https://www.britannica.com/place/Paraguay"
      },
      {
        titulo: "Equador",
        nomeOficial: "República do Equador",
        descricao: "O Equador é um país sul-americano conhecido por sua diversidade geográfica, desde a Cordilheira dos Andes até a Amazônia. Sua história é marcada pela colonização espanhola e por um período de instabilidade política. O Equador é um país com uma rica cultura, gastronomia e biodiversidade.",
        codigoISO: "ECU",
        festasNacionais: "Dia da Independência",
        capital: "Quito",
        populacao: "17.643.060",
        atualPresidente: "Guillermo Lasso",
        idioma: "Espanhol",
        monetario: "Dólar americano",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Quito_calle_Garc%C3%ADa_Moreno.jpg/640px-Quito_calle_Garc%C3%ADa_Moreno.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/640px-Flag_of_Ecuador.svg.png",
        link: "https://www.britannica.com/place/Ecuador"
      },
      {
        titulo: "Costa Rica",
        nomeOficial: "República da Costa Rica",
        descricao: "A Costa Rica é um país da América Central conhecido por seus parques nacionais, vulcões e praias. É um dos países com maior biodiversidade do mundo e um líder em conservação ambiental. Sua cultura é rica e influenciada por diversas etnias, como indígenas e afro-descendentes.",
        codigoISO: "CRI",
        festasNacionais: "Dia da Independência",
        capital: "San José",
        populacao: "5.105.100",
        atualPresidente: "Rodrigo Chaves Robles",
        idioma: "Espanhol",
        monetario: "Colón (₡)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/San_Jose_Costa_Rica_Skyline%2C_December_2023.png/640px-San_Jose_Costa_Rica_Skyline%2C_December_2023.png",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/640px-Flag_of_Costa_Rica.svg.png",
        link: "https://www.britannica.com/place/Costa-Rica"
      },
      {
        titulo: "Jamaica",
        nomeOficial: "Jamaica",
        descricao: "A Jamaica é uma ilha caribenha conhecida por suas belas praias, a rica cultura rastafári, a música reggae e o rum. Sua história está entrelaçada com a escravidão e a colonização britânica. A Jamaica é um destino turístico popular, oferecendo paisagens exuberantes, aventuras aquáticas e uma culinária deliciosa.",
        codigoISO: "JAM",
        festasNacionais: "Dia da Independência",
        capital: "Kingston",
        populacao: "2.998.722",
        atualPresidente: "Andrew Holness",
        idioma: "Inglês",
        monetario: "Dólar jamaicano ($)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/PortofKingston.jpg/640px-PortofKingston.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/1200px-Flag_of_Jamaica.svg.png?20230806021400",
        link: "https://www.britannica.com/place/Jamaica"
      },
      {
        titulo: "Porto Rico",
        nomeOficial: "Comunidade de Porto Rico",
        descricao: "Porto Rico é uma ilha caribenha com uma rica história e cultura. Influenciado por culturas indígenas, espanholas e americanas, Porto Rico oferece belas praias, uma natureza exuberante e uma vibrante cena musical. Sua relação política com os Estados Unidos é complexa, sendo um território não incorporado.",
        codigoISO: "PRI",
        festasNacionais: "Dia de San Juan Bautista",
        capital: "San Juan",
        populacao: "3.194.000",
        atualPresidente: "",
        idioma: "Espanhol e Inglês",
        monetario: "Dólar americano",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Monasterio_de_San_Juan_de_Duero%2C_Soria%2C_Espa%C3%B1a%2C_2017-05-26%2C_DD_19.jpg/640px-Monasterio_de_San_Juan_de_Duero%2C_Soria%2C_Espa%C3%B1a%2C_2017-05-26%2C_DD_19.jpg", // Substitua por uma imagem de Porto Rico
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Puerto_Rico_%281895-1952%29.svg/640px-Flag_of_Puerto_Rico_%281895-1952%29.svg.png",
        link: "https://www.britannica.com/place/Puerto-Rico"
      },
      {
        titulo: "Panamá",
        nomeOficial: "República do Panamá",
        descricao: "O Panamá é um país da América Central, conhecido pelo Canal do Panamá, uma das maiores obras de engenharia do mundo. Sua localização estratégica entre o Oceano Atlântico e o Oceano Pacífico o torna um importante centro de comércio marítimo. A cultura panamenha é uma rica mistura de influências indígenas, espanholas, afro-caribenhas e norte-americanas.",
        codigoISO: "PAN",
        festasNacionais: "Dia da Independência",
        capital: "Cidade do Panamá",
        populacao: "4.314.796",
        atualPresidente: "Laurentino Cortizo Cohen",
        idioma: "Espanhol",
        monetario: "Balboa",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Panama_city%2C_Panama_%2851274102666%29.jpg/640px-Panama_city%2C_Panama_%2851274102666%29.jpg", // Substitua por uma imagem do Panamá
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/1280px-Flag_of_Panama.svg.png",
        link: "https://www.britannica.com/place/Panama"
      },

    {
        titulo: "Estados Unidos",
        nomeOficial: "United States of America",
        descricao: "Os Estados Unidos são uma nação norte-americana composta por 50 estados e um distrito federal. Conhecido por sua diversidade cultural, economia poderosa e inovação tecnológica, os EUA são uma superpotência global",
        codigoISO: "USA",
        festasNacionais: "Dia da Independência Natal Ação de Graças Halloween",
        capital: "Washington, D.C.",
        populacao: "331.449.281",
        atualPresidente: "Joe Biden",
        idioma: "Inglês",
        monetario: "Dólar Americano ($)",
        imagem: "https://plus.unsplash.com/premium_photo-1676657955507-b1f993556e80?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        link: "https://www.britannica.com/place/United-States"
    },
    {
        titulo: "Eslováquia",
        nomeOficial: "Slovenská republika",
        descricao: "A Eslováquia é um país localizado no coração da Europa Central. Com uma rica história e cultura, a Eslováquia oferece belas paisagens, castelos medievais e cidades charmosas",
        codigoISO: "SVK",
        festasNacionais: "Dia da Constituição Eslovaca Natal",
        capital: "Bratislava",
        populacao: "5.458.827",
        atualPresidente: "Zuzana Čaputová",
        idioma: "Eslovaco",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/View_of_Bratislava_from_Nov%C3%BD_most%2C_20210727_1012_0262.jpg/640px-View_of_Bratislava_from_Nov%C3%BD_most%2C_20210727_1012_0262.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/1200px-Flag_of_Slovakia.svg.png?20221214030619",
        link: "https://www.britannica.com/place/Slovakia"
    },
    {
        titulo: "País de Gales",
        nomeOficial: "Wales",
        descricao: "O País de Gales é uma nação constituinte do Reino Unido, localizado na Grande-Bretanha. Conhecido por suas paisagens montanhosas, castelos históricos e cultura celta, o País de Gales oferece uma experiência única aos visitantes",
        codigoISO: "WLS",
        festasNacionais: "Dia de São David",
        capital: "Cardiff",
        populacao: "3.136.000",
        atualPresidente: "Vaughan Gething",
        idioma: "Galês, Inglês",
        monetario: "Libra Esterlina (£)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Cardiff_Castle_keep_2018.jpg/640px-Cardiff_Castle_keep_2018.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/640px-Flag_of_Wales.svg.png",
        link: "https://www.britannica.com/place/Wales"
    },
    {
        titulo: "Alemanha",
        nomeOficial: "República Federal da Alemanha",
        descricao: "A Alemanha é uma potência econômica da Europa, conhecida por sua história rica, cultura vibrante e engenharia avançada. Com paisagens diversificadas, desde os Alpes até o Mar do Norte, a Alemanha oferece uma variedade de experiências para seus visitantes. Suas cidades históricas, como Berlim e Munique, são destinos populares para turistas.",
        codigoISO: "DEU",
        festasNacionais: "Dia da Unidade Alemã",
        capital: "Berlim",
        populacao: "83.019.213",
        atualPresidente: "Frank-Walter Steinmeier",
        idioma: "Alemão",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Cityscape_Berlin.jpg/640px-Cityscape_Berlin.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/1280px-Flag_of_Germany.svg.png",
        link: "https://www.britannica.com/place/Germany"
      },
      {
        titulo: "Bélgica",
        nomeOficial: "Reino da Bélgica",
        descricao: "A Bélgica é um pequeno país na Europa Ocidental, conhecido por suas belas cidades, chocolate de alta qualidade, cerveja artesanal e história rica. Com paisagens diversificadas, desde as planícies até as Ardenas, a Bélgica oferece uma variedade de experiências para seus visitantes. Suas cidades históricas, como Bruxelas e Bruges, são destinos populares para turistas.",
        codigoISO: "BEL",
        festasNacionais: "Dia Nacional da Bélgica",
        capital: "Bruxelas",
        populacao: "11.589.044",
        atualPresidente: "Charles Y. J. Gh. Michel",
        idioma: "Francês Holandês Alemão",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Grote_Markt_%289379072012%29.jpg/640px-Grote_Markt_%289379072012%29.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1280px-Flag_of_Belgium.svg.png",
        link: "https://www.britannica.com/place/Belgium"
      },
      {
        titulo: "Dinamarca",
        nomeOficial: "Reino da Dinamarca",
        descricao: "A Dinamarca é um país escandinavo conhecido por sua alta qualidade de vida, design moderno, paisagens naturais exuberantes e história Viking. Com cidades charmosas como Copenhagen e cidades menores com um charme único, a Dinamarca oferece uma experiência autêntica para seus visitantes. O país é famoso por seus castelos, fiordes e pela felicidade de seus habitantes.",
        codigoISO: "DNK",
        festasNacionais: "Dia da Constituição",
        capital: "Copenhagen",
        populacao: "5.922.256",
        atualPresidente: "",
        idioma: "Dinamarquês",
        monetario: "Coroa dinamarquesa (kr)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Cityscape_and_skyline_by_the_Copenhagen_Lakes%2C_Denmark_-_%2836018109956%29.jpg/640px-Cityscape_and_skyline_by_the_Copenhagen_Lakes%2C_Denmark_-_%2836018109956%29.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1280px-Flag_of_Denmark.svg.png",
        link: "https://www.britannica.com/place/Denmark"
      },
      {
        titulo: "França",
        nomeOficial: "República Francesa",
        descricao: "A França é um país localizado na Europa Ocidental, conhecido por sua rica história, cultura e gastronomia. Paris, sua capital, é um dos destinos turísticos mais populares do mundo.",
        codigoISO: "FRA",
        festasNacionais: "Bastilha, Dia da França",
        capital: "Paris",
        populacao: "67.391.582",
        atualPresidente: "Emmanuel Macron",
        idioma: "Francês",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Eiffel_Tower_and_Pont_Alexandre_III_at_night.jpg/640px-Eiffel_Tower_and_Pont_Alexandre_III_at_night.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png",
        link: "https://www.britannica.com/place/France"
    },
    {
        titulo: "Grécia",
        nomeOficial: "República Helênica",
        descricao: "A Grécia é um país localizado no sudeste da Europa, com uma longa e rica história. Berço da civilização ocidental, a Grécia é famosa por suas ilhas, ruínas antigas e cultura vibrante.",
        codigoISO: "GRC",
        festasNacionais: "25 de Março (Dia da Independência)",
        capital: "Atenas",
        populacao: "10.423.054",
        atualPresidente: "Katerina Sakellaropoulou",
        idioma: "Grego",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Thira_%28Santorini%29_-_Ia-01.jpg/640px-Thira_%28Santorini%29_-_Ia-01.jpg", // Substitua por uma imagem da Grécia
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/1280px-Flag_of_Greece.svg.png",
        link: "https://www.britannica.com/place/Greece"
    },
    {
        titulo: "Itália",
        nomeOficial: "República Italiana",
        descricao: "A Itália é um país localizado no sul da Europa, famoso por sua rica história, arte, moda e gastronomia. Roma, sua capital, abriga o Coliseu e o Vaticano.",
        codigoISO: "ITA",
        festasNacionais: "Dia da Unidade Nacional (2 de novembro), Festa da República (2 de junho)",
        capital: "Roma",
        populacao: "60.317.096",
        atualPresidente: "Sergio Mattarella",
        idioma: "Italiano",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Leaning_Tower_of_Pisa%2C_Italy%2C_15_Sep._2023%2C_Landscape.jpg/640px-Leaning_Tower_of_Pisa%2C_Italy%2C_15_Sep._2023%2C_Landscape.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/1280px-Flag_of_Italy.svg.png",
        link: "https://www.britannica.com/place/Italy"
    },
    {
        titulo: "Polônia",
        nomeOficial: "República da Polônia",
        descricao: "A Polônia é um país localizado no centro da Europa, com uma rica história e cultura. Varsóvia, sua capital, é uma cidade moderna e vibrante.",
        codigoISO: "POL",
        festasNacionais: "Dia da Independência (11 de novembro)",
        capital: "Varsóvia",
        populacao: "37.972.811",
        atualPresidente: "Andrzej Duda",
        idioma: "Polonês",
        monetario: "Złoty (PLN)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Warsaw_07-13_img29_View_from_Palace_of_Culture_and_Science.jpg/640px-Warsaw_07-13_img29_View_from_Palace_of_Culture_and_Science.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/1280px-Flag_of_Poland.svg.png",
        link: "https://www.britannica.com/place/Poland"
    },
    {
        titulo: "Suécia",
        nomeOficial: "Reino da Suécia",
        descricao: "A Suécia é um país nórdico conhecido por suas paisagens naturais exuberantes, lagos, florestas e cidades modernas. Estocolmo, sua capital, é famosa por sua arquitetura e cultura vibrante.",
        codigoISO: "SWE",
        festasNacionais: "Dia Nacional da Suécia (6 de junho)",
        capital: "Estocolmo",
        populacao: "10.327.589",
        atualPresidente: "Sverker Olof Karl Ingemar Eriksson",
        idioma: "Sueco",
        monetario: "Coroa Sueca (SEK)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Stockholm_August_2020_-_Kastellet%2C_Vasa_Museum%2C_and_Nordic_Museum.jpg/640px-Stockholm_August_2020_-_Kastellet%2C_Vasa_Museum%2C_and_Nordic_Museum.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/1280px-Flag_of_Sweden.svg.png",
        link: "https://www.britannica.com/place/Sweden"
    },
    {
        titulo: "Suíça",
        nomeOficial: "Confederação Suíça",
        descricao: "A Suíça é um país montanhoso localizado no coração da Europa, conhecido por seus bancos, relógios, chocolate e paisagens alpinas. Berna é sua capital.",
        codigoISO: "CHE",
        festasNacionais: "Dia Nacional da Suíça (1 de agosto)",
        capital: "Berna",
        populacao: "8.702.649",
        atualPresidente: "Alain Berset",
        idioma: "Alemão, Francês, Italiano e Romanche",
        monetario: "Franco Suíço (CHF)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Central_Bern_from_north.jpg/640px-Central_Bern_from_north.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/640px-Flag_of_Switzerland.svg.png",
        link: "https://www.britannica.com/place/Switzerland"
    },
    {
        titulo: "Vaticano",
        nomeOficial: "Estado da Cidade do Vaticano",
        descricao: "O Vaticano é uma cidade-estado enclavada em Roma, sede da Igreja Católica. É o menor país do mundo e centro espiritual para bilhões de católicos.",
        codigoISO: "VAT",
        capital: "Cidade do Vaticano",
        festasNacionais: "",
        populacao: "Cerca de 800",
        atualPresidente: "Papa",
        idioma: "Italiano",
        monetario: "Euro (€)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/St_Peter%27s_Square%2C_Vatican_City_-_April_2007.jpg/640px-St_Peter%27s_Square%2C_Vatican_City_-_April_2007.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Flag_of_Vatican_City_%282023%E2%80%93present%29.svg/900px-Flag_of_Vatican_City_%282023%E2%80%93present%29.svg.png?20230805130926",
        link: "https://www.britannica.com/place/Vatican-City"
    },
    {
        titulo: "Austrália",
        nomeOficial: "Commonwealth da Austrália",
        descricao: "A Austrália é um país-continente localizado no Hemisfério Sul, conhecido por sua fauna única, como o canguru e o coala, e por suas vastas paisagens desérticas e praias. Canberra é sua capital.",
        codigoISO: "AUS",
        festasNacionais: "Dia da Austrália (26 de janeiro)",
        capital: "Canberra",
        populacao: "25.788.217",
        atualPresidente: "Anthony Albanese",
        idioma: "Inglês",
        monetario: "Dólar australiano ($)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Sydney_Opera_House_-_Dec_2008.jpg/640px-Sydney_Opera_House_-_Dec_2008.jpg", 
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/640px-Flag_of_Australia_%28converted%29.svg.png",
        link: "https://www.britannica.com/place/Australia"
    },
    {
        titulo: "Nova Zelândia",
        nomeOficial: "Nova Zelândia",
        descricao: "A Nova Zelândia é um país insular no Oceano Pacífico Sul, famoso por suas paisagens naturais exuberantes, como os Alpes do Sul e as geleiras. Wellington é sua capital.",
        codigoISO: "NZL",
        festasNacionais: "Dia de Waitangi (6 de fevereiro)",
        capital: "Wellington",
        populacao: "5.139.100",
        atualPresidente: "Chris Hipkins",
        idioma: "Inglês, Maori",
        monetario: "Dólar neozelandês ($)",
        imagem: "https://images.unsplash.com/photo-1525150521921-e8089fe8f0e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fG98fHx8fA%3D%D",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/1280px-Flag_of_New_Zealand.svg.png",
        link: "https://www.britannica.com/place/New-Zealand"
    },
    {
        titulo: "Angola",
        nomeOficial: "República de Angola",
        descricao: "Angola é um país localizado na África Austral, com uma costa atlântica extensa e uma rica biodiversidade. Luanda é sua capital.",
        codigoISO: "AGO",
        festasNacionais: "Dia da Independência (11 de novembro)",
        capital: "Luanda",
        populacao: "34.829.794",
        atualPresidente: "João Lourenço",
        idioma: "Português",
        monetario: "Kwanza (AOA)",
        imagem: "https://images.unsplash.com/photo-1525150521921-e8089fe8f0e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fG98fHx8fA%3D%D", // Substitua por uma imagem de Angola
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/1280px-Flag_of_Angola.svg.png",
        link: "https://www.britannica.com/place/Angola"
    },
    {
        titulo: "África do Sul",
        nomeOficial: "República da África do Sul",
        descricao: "A África do Sul é um país localizado na ponta sul do continente africano, conhecido por sua rica biodiversidade, paisagens variadas e pela luta contra o apartheid. Tem três capitais: Cidade do Cabo (legislativa), Pretória (administrativa) e Bloemfontein (judiciária).",
        codigoISO: "ZAF",
        festasNacionais: "Dia da Liberdade (27 de abril)",
        capital: "Cidade do Cabo, Pretória, Bloemfontein",
        populacao: "60.142.773",
        atualPresidente: "Cyril Ramaphosa",
        idioma: "Afrikaans, Inglês Zulu, Xhosa, Ndebele, Swazi, Venda, Tsonga, Tswana, Sotho do Norte, Sotho do Sul",
        monetario: "Rand sul-africano (ZAR)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Cape_Town_%28ZA%29%2C_Wale_Street_--_2024_--_3544.jpg/640px-Cape_Town_%28ZA%29%2C_Wale_Street_--_2024_--_3544.jpg", 
        bandeira: "hhttps://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/640px-Flag_of_South_Africa.svg.png",
        link: "https://www.britannica.com/place/South-Africa"
    },
    {
        titulo: "Nigéria",
        nomeOficial: "República Federal da Nigéria",
        descricao: "A Nigéria é um país da África Ocidental, conhecido por sua rica diversidade étnica e cultural, além de ser o país mais populoso da África. Abuja é sua capital.",
        codigoISO: "NGA",
        festasNacionais: "Dia da Independência (1 de outubro)",
        capital: "Abuja",
        populacao: "218.540.000",
        atualPresidente: "Bola Tinubu", 
        idioma: "Inglês, Hausa, Ioruba, Igbo",
        monetario: "Naira (NGN)",
        imagem: "https://images.unsplash.com/photo-1525150521921-e8089fe8f0e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fG98fHx8fA%3D&w=800",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/640px-Flag_of_Nigeria.svg.png",
        link: "https://www.britannica.com/place/Nigeria"
    },
    {
        titulo: "Marrocos",
        nomeOficial: "Reino de Marrocos",
        descricao: "Marrocos é um país localizado no Norte da África, conhecido por suas cidades históricas, como Marraqueche e Fez, e por suas paisagens diversas, que vão do deserto do Saara às montanhas do Atlas. Rabat é sua capital.",
        codigoISO: "MAR",
        festasNacionais: "Dia da Independência (14 de agosto)",
        capital: "Rabat",
        populacao: "37.370.958",
        atualPresidente: "Mohammed VI",
        idioma: "Árabe, Berbere",
        monetario: "Dirham marroquino (MAD)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Kasbah_des_Oudaias_P1060356.JPG/640px-Kasbah_des_Oudaias_P1060356.JPG",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/640px-Flag_of_Morocco.svg.png",
        link: "https://www.britannica.com/place/Morocco"
    },
    {
        titulo: "Egito",
        nomeOficial: "República Árabe do Egito",
        descricao: "O Egito é um país localizado no Nordeste da África, famoso por suas antigas pirâmides, o Rio Nilo e uma rica história que remonta aos faraós. O Cairo é sua capital.",
        codigoISO: "EGY",
        festasNacionais: "Dia da Revolução (23 de julho)",
        capital: "Cairo",
        populacao: "104.493.551",
        atualPresidente: "Abdel Fattah el-Sisi",
        idioma: "Árabe",
        monetario: "Libra egípcia (EGP)",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Great_Sphinx_of_Giza_%28%D8%A3%D8%A8%D9%88_%D8%A7%D9%84%D9%87%D9%88%D9%84%29.jpg/640px-Great_Sphinx_of_Giza_%28%D8%A3%D8%A8%D9%88_%D8%A7%D9%84%D9%87%D9%88%D9%84%29.jpg",
        bandeira: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/640px-Flag_of_Egypt.svg.png",
        link: "https://www.britannica.com/place/Egypt"
    }    
]